# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Galactic Dynamics Interoperability Library Maintainers
license: MIT
org: GalacticDynamics
project_name: galactic_dynamics_interoperability
project_short_description: Interoperability Between Galactic Dynamics Libraries
url: https://github.com/GalacticDynamics/galactic_dynamics_interoperability
vcs: true
